<template>
  <div class="page"><div class="page-head"><div><span class="page-kicker">PUBLISH WITH CONTROL</span><h1 class="page-title">发布中心</h1><p class="page-note">系统准备资料并打开创作者平台；账号登录和最终提交始终由你确认。</p></div><el-tag type="warning" effect="plain">人工确认模式</el-tag></div>
    <el-tabs v-model="tab" class="panel publish-tabs">
      <el-tab-pane label="发布计划" name="plans"><div class="tab-body"><section class="composer"><h3>准备一条发布计划</h3><div class="file-pick"><el-input v-model="draft.video_path" readonly placeholder="选择已经生成的视频"/><el-button @click="chooseVideo">选择视频</el-button></div><el-input v-model="draft.title" maxlength="200" show-word-limit placeholder="作品标题"/><el-select v-model="draft.platforms" multiple placeholder="发布平台"><el-option v-for="item in platforms" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-input v-model="topicText" placeholder="话题，用逗号分隔，例如：本地生活,探店"/><el-date-picker v-model="draft.schedule_time" type="datetime" placeholder="可选：计划发布时间" style="width:100%"/><el-button type="primary" @click="createPlan">保存发布计划</el-button></section>
        <section class="plan-list"><article v-for="plan in schedules" :key="plan.id" class="plan"><div class="plan-state">{{ plan.status==='draft'?'草稿':'计划' }}</div><div><strong>{{ plan.title || plan.video_path.split(/[\\/]/).pop() }}</strong><span>{{ platformNames(plan.platforms) }} · {{ plan.schedule_time?formatDate(plan.schedule_time):'未设置时间' }}</span><small>{{ plan.video_path }}</small></div><div class="plan-actions"><el-button type="primary" plain @click="prepare(plan)">准备发布</el-button><el-button text type="danger" @click="removePlan(plan.id)">删除</el-button></div></article><div v-if="!schedules.length" class="empty-state">还没有发布计划。</div></section></div></el-tab-pane>
      <el-tab-pane label="平台账号" name="accounts"><div class="tab-body accounts"><section class="composer"><h3>登记平台账号</h3><el-select v-model="account.platform" placeholder="选择平台"><el-option v-for="item in platforms" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-input v-model="account.account_name" placeholder="账号备注名称"/><el-input v-model="account.account_id" placeholder="可选：平台账号ID"/><el-button type="primary" @click="addAccount">添加账号</el-button><p>这里只记录账号名称，不保存密码、Cookie 或登录令牌。</p></section><section class="account-grid"><article v-for="item in accounts" :key="item.id" class="account-card"><span>{{ platformName(item.platform) }}</span><strong>{{ item.account_name }}</strong><small>{{ item.status==='connected'?'已连接':'登录时再确认' }}</small><el-button text type="danger" @click="removeAccount(item.id)">删除</el-button></article></section></div></el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';import { ElMessage, ElMessageBox } from 'element-plus';import api,{apiError} from '@/api'
const tab=ref('plans');const platforms=ref([]);const schedules=ref([]);const accounts=ref([]);const topicText=ref('');const draft=reactive({video_path:'',title:'',platforms:[],schedule_time:null});const account=reactive({platform:'',account_name:'',account_id:''})
async function load(){[platforms.value,schedules.value,accounts.value]=await Promise.all([(await api.get('/api/publish/platforms')).data,(await api.get('/api/publish/schedule')).data,(await api.get('/api/publish/accounts')).data])}
async function chooseVideo(){const path=await window.desktop?.selectVideoFile?.();if(path)draft.video_path=path}
async function createPlan(){if(!draft.video_path||!draft.platforms.length)return ElMessage.warning('请选择视频和发布平台');try{await api.post('/api/publish/schedule',{...draft,topics:topicText.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean),schedule_time:draft.schedule_time?.toISOString?.()||null});Object.assign(draft,{video_path:'',title:'',platforms:[],schedule_time:null});topicText.value='';await load();ElMessage.success('发布计划已保存')}catch(error){ElMessage.error(apiError(error))}}
async function prepare(plan){const {data}=await api.post(`/api/publish/schedule/${plan.id}/prepare`);await ElMessageBox.confirm('即将打开所选平台的创作者中心。请登录后核对视频、标题和话题，再由你点击最终发布。','准备发布',{confirmButtonText:'打开平台',type:'warning'});for(const item of data.platforms)await window.desktop?.openExternal?.(item.creator_url)}
async function removePlan(id){try{await api.delete(`/api/publish/schedule/${id}`);await load()}catch(error){ElMessage.error(apiError(error))}}
async function addAccount(){if(!account.platform||!account.account_name)return ElMessage.warning('请选择平台并填写账号名称');try{await api.post('/api/publish/accounts',account);Object.assign(account,{platform:'',account_name:'',account_id:''});await load()}catch(error){ElMessage.error(apiError(error))}}
async function removeAccount(id){try{await api.delete(`/api/publish/accounts/${id}`);await load()}catch(error){ElMessage.error(apiError(error))}}
function platformName(id){return platforms.value.find(item=>item.id===id)?.name||id}function platformNames(ids){return ids.map(platformName).join('、')}function formatDate(value){return new Date(value).toLocaleString('zh-CN',{hour12:false})}
onMounted(()=>load().catch(error=>ElMessage.error(apiError(error))))
</script>

<style scoped>
.publish-tabs{padding:8px 20px 20px}.tab-body{display:grid;grid-template-columns:310px 1fr;gap:23px;padding:13px 2px}.composer{display:flex;flex-direction:column;gap:11px;padding-right:22px;border-right:1px solid var(--line)}.composer h3{margin:0 0 8px;font-family:"STZhongsong",serif}.composer p{color:var(--muted);font-size:10px;line-height:1.7}.file-pick{display:flex;gap:7px}.plan{display:grid;grid-template-columns:50px 1fr auto;gap:13px;align-items:center;padding:15px 0;border-bottom:1px solid var(--line)}.plan-state{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(244,185,66,.25);border-radius:50%;color:var(--amber);font-size:10px}.plan strong,.plan span,.plan small{display:block}.plan strong{font-size:12px}.plan span{margin:5px 0;color:#8da2b4;font-size:10px}.plan small{max-width:500px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#536a7d;font-size:8px}.account-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;align-content:start}.account-card{padding:19px;border:1px solid var(--line);border-radius:12px;background:rgba(7,16,27,.35)}.account-card span,.account-card strong,.account-card small{display:block}.account-card span{color:var(--teal);font-size:9px}.account-card strong{margin:12px 0 5px}.account-card small{color:var(--muted);font-size:9px}.account-card .el-button{margin-top:10px;padding:0}@media(max-width:1000px){.tab-body{grid-template-columns:1fr}.composer{border:0;padding:0 0 20px;border-bottom:1px solid var(--line)}.account-grid{grid-template-columns:repeat(2,1fr)}}
</style>

