<template>
  <div class="page settings-page"><div class="page-head"><div><span class="page-kicker">LOCAL PREFERENCES</span><h1 class="page-title">系统设置</h1><p class="page-note">API Key 使用 Electron 安全存储，不写入项目文件或 SQLite。</p></div><el-button type="primary" :loading="saving" @click="save">保存设置</el-button></div>
    <div class="settings-grid"><section class="panel panel-pad"><div class="setting-title"><el-icon><MagicStick /></el-icon><div><h3>AI 文案服务</h3><p>用于生成门店短视频脚本。</p></div></div><el-form label-position="top"><el-form-item label="百炼 API Key"><el-input v-model="apiKey" type="password" show-password placeholder="sk-…" autocomplete="off"/></el-form-item><el-form-item label="模型"><el-input v-model="form.ai_model" placeholder="qwen-plus"/></el-form-item><div class="toolbar"><el-button :loading="testing" @click="testAI">测试连接</el-button><span :class="['test-state',test.ok?'ok':'']">{{ test.message }}</span></div></el-form></section>
      <section class="panel panel-pad"><div class="setting-title"><el-icon><Monitor /></el-icon><div><h3>桌面行为</h3><p>控制应用在 Windows 中的启动和退出方式。</p></div></div><div class="switch-row"><div><strong>开机自动启动</strong><span>登录 Windows 后自动打开工作台</span></div><el-switch v-model="form.auto_start"/></div><div class="switch-row"><div><strong>关闭时最小化到托盘</strong><span>后台任务进行时避免误退出</span></div><el-switch v-model="form.minimize_to_tray"/></div><div class="switch-row"><div><strong>默认发布间隔</strong><span>连续处理发布计划时的提醒间隔</span></div><el-input-number v-model="form.publish_interval" :min="5" :max="1440"/></div></section>
      <section class="panel panel-pad full"><div class="setting-title"><el-icon><InfoFilled /></el-icon><div><h3>能力与边界</h3><p>当前版本不会偷偷替你点击最终发布。</p></div></div><div class="capabilities"><span><b></b>本地素材扫描</span><span><b></b>FFmpeg 真实合成</span><span><b></b>批量生成队列</span><span><b></b>MIT 社区版</span><span class="manual"><b></b>平台发布：人工确认</span></div></section></div>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';import { ElMessage } from 'element-plus';import api,{apiError} from '@/api'
const saving=ref(false);const testing=ref(false);const apiKey=ref('');const form=reactive({auto_start:false,minimize_to_tray:true,publish_interval:30,theme:'dark',language:'zh-CN',ai_provider:'dashscope',ai_model:'qwen-plus'});const test=reactive({ok:false,message:'尚未测试'})
onMounted(async()=>{try{Object.assign(form,(await api.get('/api/settings')).data);apiKey.value=await window.desktop?.getSecret?.('dashscope_api_key')||''}catch(error){ElMessage.error(apiError(error,'设置加载失败'))}})
async function save(){saving.value=true;try{await api.put('/api/settings',form);await window.desktop?.setSecret?.('dashscope_api_key',apiKey.value);await window.desktop?.setAutoStart?.(form.auto_start);await window.desktop?.setMinimizeToTray?.(form.minimize_to_tray);ElMessage.success('设置已保存')}catch(error){ElMessage.error(apiError(error))}finally{saving.value=false}}
async function testAI(){if(!apiKey.value)return ElMessage.warning('请先填写 API Key');testing.value=true;test.message='正在连接…';try{const {data}=await api.post('/api/ai/script',{topic:'用一句话介绍门店',api_key:apiKey.value,model:form.ai_model});test.ok=data.success;test.message=data.success?'连接成功':'连接失败'}catch(error){test.ok=false;test.message=apiError(error,'连接失败')}finally{testing.value=false}}
</script>

<style scoped>
.settings-page{max-width:980px}.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.setting-title{display:flex;gap:13px;align-items:center;padding-bottom:18px;margin-bottom:19px;border-bottom:1px solid var(--line)}.setting-title>.el-icon{font-size:24px;color:var(--amber)}.setting-title h3,.setting-title p{margin:0}.setting-title h3{font-family:"STZhongsong",serif}.setting-title p{margin-top:4px;color:var(--muted);font-size:10px}.test-state{color:var(--muted);font-size:10px}.test-state.ok{color:var(--teal)}.switch-row{min-height:67px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.switch-row:last-child{border:0}.switch-row strong,.switch-row span{display:block}.switch-row strong{font-size:12px}.switch-row span{margin-top:4px;color:var(--muted);font-size:9px}.full{grid-column:1/-1}.capabilities{display:flex;flex-wrap:wrap;gap:10px}.capabilities span{padding:8px 11px;border:1px solid var(--line);border-radius:9px;color:#a9bdcc;font-size:10px}.capabilities b{display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:var(--teal)}.capabilities .manual b{background:var(--amber)}@media(max-width:850px){.settings-grid{grid-template-columns:1fr}.full{grid-column:auto}}
</style>

